all_strategies:
  - ema
  - rsi
  - macd
  - bollinger
  - trend_score

ml_filter:
  enabled: false
  model_path: ml_filter_model.pkl
ml_threshold: 0.6

symbols_source: top_200_coinex

timeframe: 5min
limit: 300
initial_capital: 10
threshold: 0.5
live: false
coinex:
  api_key: "ECEA61495F674384A6E6189D055237C2"
  api_secret: "9BFDD9508764F762EDC7FFC279CC1D2A973622ED7FEA548D"
trailing_stop_pct: 0.03
trailing_trigger_pct: 0.02
